spring:
  application:
    name: GreetService
  boot:
    admin:
      client:
        url:
        - http://localhost:1111
  config:
    import: optional:configserver:http://localhost:9093
server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'

      